import { useEffect,useState } from "react";
import { Alert,Box,Button,Card,CardContent,Chip,CircularProgress,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography } from "@mui/material";
import { consoleGet, type ConsolePage } from "../api/console";

export default function ConsolePage({title,path}:{title:string;path:string}){
 const [data,setData]=useState<ConsolePage|Record<string,unknown>|null>(null);const [q,setQ]=useState("");const [error,setError]=useState(false);const [offset,setOffset]=useState(0);
 useEffect(()=>{setData(null);setError(false);consoleGet(`${path}${path.includes("?")?"&":"?"}offset=${offset}&limit=25${q?`&q=${encodeURIComponent(q)}`:""}`).then(setData).catch(()=>setError(true));},[path,offset,q]);
 if(error)return <Alert severity="error">Unable to load persisted auditor data.</Alert>;if(!data)return <Box sx={{p:4,textAlign:"center"}}><CircularProgress/></Box>;
 const page="items" in data ? data as ConsolePage : null; const items=page?page.items:[]; const columns=items[0]?Object.keys(items[0]).filter(k=>!["results","evidence","unknown_patterns","metadata_provenance"].includes(k)).slice(0,10):[];
 return <Stack spacing={2}><Box><Typography variant="overline" color="secondary.main">PERSISTENT AUDITOR CONSOLE</Typography><Typography variant="h4">{title}</Typography></Box><TextField size="small" label="Search persisted records" value={q} onChange={e=>{setQ(e.target.value);setOffset(0)}}/><Card><CardContent>{!page?<pre>{JSON.stringify(data,null,2)}</pre>:items.length===0?<Typography color="text.secondary">No persisted records match this view.</Typography>:<><Table size="small"><TableHead><TableRow>{columns.map(c=><TableCell key={c}>{c.replaceAll("_"," ")}</TableCell>)}</TableRow></TableHead><TableBody>{items.map((item,i)=><TableRow key={String(item.analysis_id??item.device_id??item.configuration_id??item.batch_id??i)}>{columns.map(c=><TableCell key={c}>{typeof item[c]==="object"?<Chip size="small" label={JSON.stringify(item[c]).slice(0,56)}/>:String(item[c]??"—")}</TableCell>)}</TableRow>)}</TableBody></Table><Stack direction="row" justifyContent="space-between" sx={{mt:2}}><Typography variant="caption">{page.total} persisted records</Typography><Stack direction="row" spacing={1}><Button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</Button><Button disabled={offset+page.limit>=page.total} onClick={()=>setOffset(offset+25)}>Next</Button></Stack></Stack></>}</CardContent></Card></Stack>;
}
