# SYNTHETIC DEMONSTRATION CONFIGURATION — FortiGate/FortiOS non-compliant case
#config-version=FGT60F v7.4.3,build2573
config system global
    set hostname "demo-fortigate-noncompliant"
end
config system interface
    edit "port1"
        set allowaccess ping https telnet
    next
end
config log disk setting
    set status disable
end
config system password-policy
    set status disable
end
config system ntp
    set ntpsync disable
end
