# SYNTHETIC DEMONSTRATION CONFIGURATION — Palo Alto PAN-OS compliant case
set deviceconfig system hostname demo-paloalto-compliant
set network profiles interface-management-profile mgmt-secure ssh yes
set network profiles interface-management-profile mgmt-secure telnet no
set network interface ethernet ethernet1/1 layer3 interface-management-profile mgmt-secure
set shared log-settings system match-list system-audit send-to-panorama yes
set mgt-config password-complexity block-username-inclusion yes
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address 192.0.2.10
